Add Python typechecking with mypy (#1617)
* Add mypy config

Co-authored-by: Nakul Verma <173621577+nakul-py@users.noreply.github.com>

* Expand typecheck workflow to typecheck from root project

* Fixup name of typecheck workflow

* Properly install everything to typecheck :X

* Attempt to fixup validation error in CI

```
 Invalid workflow file: .github/workflows/typecheck-python.yml#L1
(Line: 38, Col: 16): Unexpected symbol: '"package'. Located at position 11 within expression: hashFiles("package.json")
```

* Install all dependency groups in dev install

* Use correct dependency group in CI

* Upgrade to jupyter-tiler with py.typed marker

I was sure I did this... ¯\_(ツ)_/¯

* Add stubs for geopandas

* Fix incorrect annotations in explore module

* Fix incorrect annotation in gis_document module

* Ignore missing imports from sidecar

* Fix typechecker complains in gis_document module

* Avoid use of pydantic constrained types in generated types

Without this change, generated code would include function calls to e.g.
[confloat](https://pydantic.dev/docs/validation/2.4/api/pydantic/types/#pydantic.types.confloat)
and that's not allowed in type expressions by the Pythong typing
specification (this was a recent clarification of the spec).

Resolves errors like this:

```
python/jupytergis_core/jupytergis_core/schema/interfaces/project/layers/geoTiffLayer.py:50: error: Invalid type comment or annotation  [valid-type]
python/jupytergis_core/jupytergis_core/schema/interfaces/project/layers/geoTiffLayer.py:50: note: Cannot use a function call in a type annotation
```

<https://github.com/koxudaxi/datamodel-code-generator/issues/2313>

* Ignore missing imports / type information from several dependencies

* Remove redundant default values and use default factory instead

* Fixup annotations in core.handler module

* Avoid using temporary variable

`layers` is typed as `IGrammarLayer` earlier

* Make typeguard explicit

* Fixup some type annotations

* Honor commitment to return a Self when subclassed

The alternative is to update the annotation to -> "GrammarSymbology",
which may be more correct. But it was annotated as -> Self, so I updated
the runtime code to correctly return a Self. The difference only
manifests when subclassing.

* Correctly pass an RGBA instance instead of list of floats

* Add missing type info

* Factor out WhenInput

When using argument unpacking with splat, our type annotation represents
a singular. If we package the singular, the plural, and None under a
single WhenInput alias, sometimes we need to use a component of
WhenInput (e.g. `*when`), and sometimes we use all of WhenInput. It hides information
that's important for readability, and a reader would need to memorize
what WhenInput represents to comprehend the code.

* Factor out VisualEncodings type

For same reason as factoring out WhenInput. Sometimes we need plural and
sometimes we need singular, and combining them makes the code more
confusing!

* Ignore type errors when we intentionally use magic methods to defined a "DSL"

* Add return type annotation to __init__ methods

Only really necessary for the first one, which mypy reads as "untyped",
but why not do them all?

* Replace dynamic enum generation with typechecker-friendly hand-managed Enum

Plus unit tests to ensure it doesn't get out of sync!

* Fix incorrect annotation

* Add PyQt5 type stubs

* Follow unused imports for webcolors

I don't follow the reasoning, but webcolors' author refuses to include a
py.typed marker, and the stubs package is out of date (and besides, just
duplicates information already in the package).

Perhaps another reason for us to drop this dependency!

See <https://github.com/ubernostrum/webcolors/issues/19>

* Add missing annotation

* Fixup incorrect annotations

* Fixup round call on values typed as string

* Fixup incorrect annotation using lots of casts :(

* Fixup incorrect type annotation

A TypedDict or other stricter type would be better. Figure it out later.

* Fixup type annotations and catch invalid state early

* Correctly specify types for qgis_layer_to_jgis

* Fixup incorrect annotation

* Ignore possible bug in typechecker

* Fixup type annotation

* Avoid generating constrained type

patternProperties is not useful when the pattern is a total wildcard.
Plus it yields a Python type which a function call in the type
signature, which is not cool.

* Handle Path or str in get_gpkg_layers

* Fix/add type annotations and typeguards in grammar module

* Fixup type of color object

* Fixup types in migration script

* Remove redundant default from schema

Difference in rendered output is use of default factory instead of dict:

```diff
94,95c94,95
<         Content | None, Field(default_factory=Content, title='Segment Content')
<     ]
---
>         Content | None, Field(title='Segment Content', validate_default=True)
>     ] = {'contentMode': 'map', 'title': '', 'image': ''}
```

The dict default was the source of the type error this resolves:

```
python/jupytergis_core/jupytergis_core/schema/interfaces/project/layers/storySegmentLayer.py:95: error: Incompatible types in assignment (expression has type "dict[str, str]", variable has type "Content | None")  [assignment]
```

* Lint :bell:

* Add and fix annotations in qgis data_defined module

* Replace dev dependency group with build group for typechecking env

* Remove VisualEncodings type from autodoc

* Add observability when jupyter labextension list checks fail

Also add yarn caching

* Update .github/workflows/typecheck-python.yml

Co-authored-by: Nakul Verma <nakulverma.py@gmail.com>

* Remove unused python-version matrix references

* Fixup incorrect dependency group

* Build types from schema instead of building whole package

* Switch to build:schema task -- this one will download the needed GeoJSON schema

* Use dev install script to install all python packages and deps

Should resolve errors:

```
python/jupytergis_core/jupytergis_core/color_ramps.py:10: error: Cannot find implementation or library stub for module named "branca.colormap"  [import-not-found]
python/jupytergis_lab/jupytergis_lab/notebook/y_connector.py:4: error: Cannot find implementation or library stub for module named "ypywidgets"  [import-not-found]
python/jupytergis_core/jupytergis_core/tests/test_colors.py:1: error: Cannot find implementation or library stub for module named "pytest"  [import-not-found]
python/jupytergis_qgis/jupytergis_qgis/qgis_ydoc.py:7: error: Cannot find implementation or library stub for module named "jupyter_ydoc.ybasedoc"  [import-not-found]
python/jupytergis_qgis/jupytergis_qgis/qgis_ydoc.py:9: error: Cannot find implementation or library stub for module named "pycrdt"  [import-not-found]
python/jupytergis_core/jupytergis_core/tests/test_migrations.py:15: error: Cannot find implementation or library stub for module named "pytest"  [import-not-found]
python/jupytergis_core/jupytergis_core/jgis_ydoc.py:6: error: Cannot find implementation or library stub for module named "jupyter_ydoc.ybasedoc"  [import-not-found]
python/jupytergis_core/jupytergis_core/jgis_ydoc.py:7: error: Cannot find implementation or library stub for module named "pycrdt"  [import-not-found]
python/jupytergis_qgis/jupytergis_qgis/tests/test_qgis.py:5: error: Cannot find implementation or library stub for module named "dirty_equals"  [import-not-found]
python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py:44: error: Cannot find implementation or library stub for module named "pycrdt"  [import-not-found]
python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py:47: error: Cannot find implementation or library stub for module named "ypywidgets.comm"  [import-not-found]
python/jupytergis_lab/jupytergis_lab/notebook/gis_document.py:56: error: Cannot find implementation or library stub for module named "jupyter_tiler.titiler"  [import-not-found]
python/jupytergis_lab/jupytergis_lab/__init__.py:2: error: Cannot find implementation or library stub for module named "jupytergis_lab._version"  [import-not-found]
python/jupytergis_lab/jupytergis_lab/notebook/tests/test_api.py:1: error: Cannot find implementation or library stub for module named "pytest"  [import-not-found]
python/jupytergis_qgis/jupytergis_qgis/__init__.py:2: error: Cannot find implementation or library stub for module named "jupytergis_qgis._version"  [import-not-found]
python/jupytergis_core/jupytergis_core/__init__.py:2: error: Cannot find implementation or library stub for module named "jupytergis_core._version"  [import-not-found]
python/jupytergis_core/jupytergis_core/__init__.py:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

* Add jlpm before using it

* Use variable where variable should have been used

* Use kwarg-only sentinel :star:

* Try removing `--use-default-factory-for-optional-nested-models` arg

I added this in 244c91baf786ddac394fe515d30ebfe9cf86a1b6 but I didn't
clearly document why. Now it's causing a problem (see
<https://github.com/geojupyter/jupytergis/pull/1617#issuecomment-5013691635>).
Removing it doesn't seem to cause a regression. I'm not really sure what
I was orinally trying to solve, so we'll see what happens.

* fix parquet tests

* remove explict loop

---------

Co-authored-by: Nakul Verma <173621577+nakul-py@users.noreply.github.com>
Co-authored-by: martinRenou <martin.renou@gmail.com>
Co-authored-by: Nakul Verma <nakulverma.py@gmail.com>