Remove redundant default from schema
Difference in rendered output is use of default factory instead of dict:

```diff
94,95c94,95
<         Content | None, Field(default_factory=Content, title='Segment Content')
<     ]
---
>         Content | None, Field(title='Segment Content', validate_default=True)
>     ] = {'contentMode': 'map', 'title': '', 'image': ''}
```

The dict default was the source of the type error this resolves:

```
python/jupytergis_core/jupytergis_core/schema/interfaces/project/layers/storySegmentLayer.py:95: error: Incompatible types in assignment (expression has type "dict[str, str]", variable has type "Content | None")  [assignment]
```